#pragma once
#include "CitiesAndRegions.h"
#include "Editor.h"
#include "EditorInterfaces.h"
#include "TextFileTable.h"
#include "ExtendedEntities.h"
#include "DatabaseOptions.h"
#include "Translation.h"
#include "Utils.h"
#include "FifamGeoCoords.h"

UChar CityCombobox[0x54];

Map<Int, DBCity> &DBCities() {
    static Map<Int, DBCity> dbCities;
    return dbCities;
}

Map<Int, DBRegion> &DBRegions() {
    static Map<Int, DBRegion> dbRegions;
    return dbRegions;
}

Array<Map<String, DBCity>, 208> &AutogeneratedCitiesDb() {
    static Array<Map<String, DBCity>, 208> autogeneratedCitiesDb;
    return autogeneratedCitiesDb;
}

DBCity *GetCity(Int id) {
    if (Utils::Contains(DBCities(), id))
        return &DBCities()[id];
    return nullptr;
}

DBRegion *GetRegion(Int id) {
    if (Utils::Contains(DBRegions(), id))
        return &DBRegions()[id];
    return nullptr;
}

void ReadCities(Path const &dbFolder) {
    TextFileTable file;
    Path fileName = dbFolder / "Cities.txt";
    if (!file.ReadUnicodeText(fileName))
        return; // failed to read file
    if (file.Rows().size() > 1) {
        for (size_t i = 1; i < file.Rows().size(); i++) {
            if (file.Rows()[i - 1].size() != file.Rows()[i].size()) {
                ::Error(L"Error in Cities file: " + fileName.wstring() + Utils::Format(L"at row %u (%u/%u)", i,
                    file.Rows()[i - 1].size(), file.Rows()[i].size()));
                return;
            }
        }
    }
    if (!file.IsConsistent() || file.NumRows() < 1 || file.NumColumns(0) < 2)
        return; // wrong file format
    if (file.NumRows() < 2)
        return; // empty file
    auto header = file.Row(0);
    Int languageColumnIndexes[NUM_TRANSLATION_LANGUAGES] = {};
    Int defaultColumnIndex = -1;
    for (UInt i = 0; i < NUM_TRANSLATION_LANGUAGES; i++)
        languageColumnIndexes[i] = -1;
    for (UInt columnIndex = 8; columnIndex < header.size(); columnIndex++) {
        auto columnName = ToLower(header[columnIndex]);
        Bool isDefaultColumn = false;
        if (defaultColumnIndex == -1) {
            if (columnName == L"default" || columnName == L"def") {
                defaultColumnIndex = columnIndex;
                isDefaultColumn = true;
            }
        }
        if (!isDefaultColumn) {
            Int languageId = GetTranslationLanguageID(columnName);
            if (languageId != -1)
                languageColumnIndexes[languageId] = columnIndex;
        }
    }
    for (UInt row = 1; row < file.NumRows(); row++) {
        DBCity city;
        city.id = Utils::SafeConvertInt<Int>(file.Cell(0, row));
        Int countryId = Utils::SafeConvertInt<Int>(file.Cell(1, row));
        city.countryId = (countryId == -1) ? 0 : (UChar)countryId;
        city.population = Utils::SafeConvertInt<UChar>(file.Cell(3, row));
        city.latitude = Utils::SafeConvertFloat(file.Cell(4, row));
        city.longitude = Utils::SafeConvertFloat(file.Cell(5, row));
        city.regionId = Utils::SafeConvertInt<Int>(file.Cell(6, row));
        for (UInt lang = 0; lang < NUM_TRANSLATION_LANGUAGES; lang++) {
            if (languageColumnIndexes[lang] != -1)
                city.names[lang] = file.Cell(languageColumnIndexes[lang], row);
            else if (defaultColumnIndex != -1)
                city.names[lang] = file.Cell(defaultColumnIndex, row);
        }
        DBCities()[city.id] = city;
    }
}

void WriteCities(CCompleteWorld *world, Path const &dbFolder) {
    TextFileTable file;
    file.AddRow(L"ID", L"CountryID", L"CountryName", L"Population", L"Latitude", L"Longitude", L"Region", L"RegionName",
        L"default", L"fre", L"ger", L"ita", L"spa", L"pol");
    for (auto const &[id, city] : DBCities()) {
        file.AddRow(city.id, city.countryId, world->GetCountry(city.countryId)->GetName(),
            0, city.latitude, city.longitude, -1, L"",
            city.names[TRANSLATIONLANGUAGE_ENG], city.names[TRANSLATIONLANGUAGE_FRE], city.names[TRANSLATIONLANGUAGE_GER],
            city.names[TRANSLATIONLANGUAGE_ITA], city.names[TRANSLATIONLANGUAGE_SPA], city.names[TRANSLATIONLANGUAGE_POL]);
    }
    file.WriteUnicodeText(dbFolder / "Cities.txt");
}

void ReadRegions(Path const &dbFolder) {
    TextFileTable file;
    Path fileName = dbFolder / "Regions.txt";
    if (!file.ReadUnicodeText(fileName))
        return; // failed to read file
    if (file.Rows().size() > 1) {
        for (size_t i = 1; i < file.Rows().size(); i++) {
            if (file.Rows()[i - 1].size() != file.Rows()[i].size()) {
                ::Error(L"Error in Cities file: " + fileName.wstring() + Utils::Format(L"at row %u (%u/%u)", i,
                    file.Rows()[i - 1].size(), file.Rows()[i].size()));
                return;
            }
        }
    }
    if (!file.IsConsistent() || file.NumRows() < 1 || file.NumColumns(0) < 2)
        return; // wrong file format
    if (file.NumRows() < 2)
        return; // empty file
    auto header = file.Row(0);
    Int languageColumnIndexes[NUM_TRANSLATION_LANGUAGES] = {};
    Int defaultColumnIndex = -1;
    for (UInt i = 0; i < NUM_TRANSLATION_LANGUAGES; i++)
        languageColumnIndexes[i] = -1;
    for (UInt columnIndex = 8; columnIndex < header.size(); columnIndex++) {
        auto columnName = ToLower(header[columnIndex]);
        Bool isDefaultColumn = false;
        if (defaultColumnIndex == -1) {
            if (columnName == L"default" || columnName == L"def") {
                defaultColumnIndex = columnIndex;
                isDefaultColumn = true;
            }
        }
        if (!isDefaultColumn) {
            Int languageId = GetTranslationLanguageID(columnName);
            if (languageId != -1)
                languageColumnIndexes[languageId] = columnIndex;
        }
    }
    for (UInt row = 1; row < file.NumRows(); row++) {
        DBRegion region;
        region.id = Utils::SafeConvertInt<Int>(file.Cell(0, row));
        region.countryId = Utils::SafeConvertInt<UChar>(file.Cell(1, row));
        region.latitude = Utils::SafeConvertFloat(file.Cell(3, row));
        region.longitude = Utils::SafeConvertFloat(file.Cell(4, row));
        for (UInt lang = 0; lang < NUM_TRANSLATION_LANGUAGES; lang++) {
            if (languageColumnIndexes[lang] != -1)
                region.names[lang] = file.Cell(languageColumnIndexes[lang], row);
            else if (defaultColumnIndex != -1)
                region.names[lang] = file.Cell(defaultColumnIndex, row);
        }
        DBRegions()[region.id] = region;
    }
}

void ReadCitiesAndRegions(Path const &dbFolder) {
    ReadRegions(dbFolder);
    ReadCities(dbFolder);
}

void *METHOD OnDlgClubConstructor(void *t, DUMMY_ARG, UShort id, void *parent) {
    CallMethod<0x4133C0>(t, id, parent); // CDialogB::CDialogB
    ComboBoxConstruct(CityCombobox);
    return t;
}

void *METHOD OnDlgClubDestructor(void *t) {
    ComboBoxDestruct(CityCombobox);
    CallMethod<0x401380>(t); // CDialogB::~CDialogB
    return t;
}

void METHOD OnDlgClubDoDataExchange(void *t, DUMMY_ARG, void *pDX) {
    CallMethod<0x429350>(t, pDX); // CDlgClub::DoDataExchange
    DDX_Control(pDX, 3000, CityCombobox);
}

WideChar ClubOldTownName[6][30] = {};
Int ClubLatitude = 0;
Int NewCityId = 2100000001;

Bool METHOD OnReadClubTown(CKLFile *file, DUMMY_ARG, WideChar *out, UInt count, UInt maxLen) {
    auto club = raw_ptr(out, -0x454);
    if (!file->IsVersionGreaterOrEqual(0x2013, 0x12))
        return file->ReadStringArray(ClubOldTownName, count, maxLen);
    else
        memset(ClubOldTownName, 0, sizeof(ClubOldTownName));
    return true;
}

Bool METHOD OnReadClubAddress(CKLFile *file, DUMMY_ARG, WideChar *out, UInt maxLen) {
    auto club = raw_ptr(out, -0xD90);
    Bool result = true;
    if (file->IsVersionGreaterOrEqual(0x2013, 0x12))
        result = file->ReadInt(GetClubExtension(club)->cityId);
    return file->ReadString(out, maxLen) && result;
}

Bool METHOD OnReadClubLatitude(CKLFile *file, DUMMY_ARG, Int *pLatitude, WideChar sep) {
    ClubLatitude = 0;
    Bool result = file->ReadIntAndDelimiter(pLatitude, sep);
    if (result)
        ClubLatitude = *pLatitude;
    return result;
}

Bool METHOD OnReadClubLongitude(CKLFile *file, DUMMY_ARG, Int *pLongitude) {
    Bool result = file->ReadInt(pLongitude);
    if (!file->IsVersionGreaterOrEqual(0x2013, 0x12) && DBCities().empty()) {
        auto club = raw_ptr(pLongitude, -0x3844);
        UChar countryId = *raw_ptr<UChar>(club, 0xA);
        auto &countryCities = AutogeneratedCitiesDb()[countryId];
        String cityName = ClubOldTownName[EDITORTRANSLATION_ENG];
        Int cityId = -1;
        auto it = countryCities.find(cityName);
        if (it == countryCities.end()) {
            auto &city = countryCities[cityName];
            city.id = NewCityId++;
            city.countryId = countryId;
            FifamGeoCoords coords(ClubLatitude, *pLongitude);
            city.latitude = coords.mLatitude.ToFloat();
            city.longitude = coords.mLongitude.ToFloat();
            city.names[TRANSLATIONLANGUAGE_ENG] = ClubOldTownName[EDITORTRANSLATION_ENG];
            city.names[TRANSLATIONLANGUAGE_FRE] = ClubOldTownName[EDITORTRANSLATION_FRE];
            city.names[TRANSLATIONLANGUAGE_GER] = ClubOldTownName[EDITORTRANSLATION_GER];
            city.names[TRANSLATIONLANGUAGE_ITA] = ClubOldTownName[EDITORTRANSLATION_ITA];
            city.names[TRANSLATIONLANGUAGE_SPA] = ClubOldTownName[EDITORTRANSLATION_SPA];
            city.names[TRANSLATIONLANGUAGE_POL] = ClubOldTownName[EDITORTRANSLATION_POL];
            for (UInt lang = NUM_DEFAULT_TRANSLATION_LANGUAGES; lang < NUM_TRANSLATION_LANGUAGES; lang++)
                city.names[lang] = cityName;
            cityId = city.id;
        }
        else
            cityId = (*it).second.id;
        GetClubExtension(club)->cityId = cityId;
    }
    return result;
}

Bool METHOD OnWriteClubAddress(CKLFile *file, DUMMY_ARG, WideChar const *str) {
    auto club = raw_ptr(str, -0xD90);
    Bool result = file->WriteInt(GetClubExtension(club)->cityId);
    result = file->WriteString(str) && result;
    return result;
}

Bool METHOD OnLoadDatabase(CCompleteWorld *world, DUMMY_ARG, WideChar const *databasePath) {
    Bool result = CallMethodAndReturn<Bool, 0x4D3F90>(world, databasePath); // CCompleteWorld::Load
    Bool autogenerateCities = false;
    for (auto const &i : AutogeneratedCitiesDb()) {
        for (auto const &[id, city] : i)
            DBCities()[city.id] = city;
    }
    return result;
}

void METHOD OnSaveDatabase(CCompleteWorld *world, DUMMY_ARG, void *ltes) {
    CallMethod<0x4CE7E0>(world, ltes); // CCompleteWorld::Save
    Bool writeCities = false;
    for (auto const &i : AutogeneratedCitiesDb()) {
        if (!i.empty()) {
            writeCities = true;
            break;
        }
    }
    if (writeCities)
        WriteCities(world, DatabaseFolderName);
}

void METHOD OnDlgClubLoadClub(void *t, DUMMY_ARG, CClub *club, CCountry *country) {
    if (club) {
        SendMessageW(ComboBoxHWND(CityCombobox), CB_RESETCONTENT, 0, 0);
        ComboBoxAddItem(CityCombobox, L"-", -1);
        ComboBoxSetCurrentItem(CityCombobox, -1);
        Vector<DBCity const *> countryCities;
        Int clubCityID = GetClubExtension(club)->cityId;
        Bool hasClubCity = false;
        for (auto const &[id, city] : DBCities()) {
            if (city.countryId == country->GetID()) {
                ComboBoxAddItem(CityCombobox, city.names[CurrentLanguageId].c_str(), city.id);
                if (city.id == clubCityID)
                    hasClubCity = true;
            }
        }
        if (!hasClubCity && Utils::Contains(DBCities(), clubCityID)) {
            ComboBoxAddItem(CityCombobox, DBCities()[clubCityID].names[CurrentLanguageId].c_str(), clubCityID);
            hasClubCity = true;
        }
        if (hasClubCity)
            ComboBoxSetCurrentItem(CityCombobox, clubCityID);
    }
    CallMethod<0x42B0A0>(t, club, country);
}

void METHOD OnDlgClubSaveClub(void *t) {
    CallMethod<0x42A240>(t);
    auto club = *raw_ptr<void *>(t, 0x3CC8);
    if (club)
        GetClubExtension(club)->cityId = ComboBoxGetCurrentItem(CityCombobox, -1);
}

WideChar const *METHOD OnGetClubTownName(CClub *club) {
    auto city = GetCity(GetClubExtension(club)->cityId);
    if (city)
        return city->names[EditorLanguageToTranslationLanguage[club->GetWorld()->GetCurrentLanguage()]].c_str();
    return L"";
}

WideChar const *METHOD OnGetClubTownName_NameEditor(CClub *club, DUMMY_ARG, Int editorLanguageId) {
    return L"";
}

WideChar const *METHOD OnGetClubTownName_DatabaseProblemTool(CClub *club, DUMMY_ARG, Int editorLanguageId) {
    auto city = GetCity(GetClubExtension(club)->cityId);
    if (city)
        return city->names[editorLanguageId].c_str(); // use ID directly here - the order doesn't matter here
    return L"";
}

WideChar const *METHOD OnGetClubName_DatabaseProblemTool(CClub *club, DUMMY_ARG, Int editorLanguageId) {
    if (!IsDefaultTranslationLanguage(editorLanguageId)) // ignore non-default languages
        return L"";
    return club->GetName(editorLanguageId);
}

WideChar const *METHOD OnGetClubTownName_AllOther(CClub *club, DUMMY_ARG, Int editorLanguageId) {
    auto city = GetCity(GetClubExtension(club)->cityId);
    if (city)
        return city->names[EditorLanguageToTranslationLanguage[editorLanguageId]].c_str();
    return L"";
}

void METHOD ClubSetTownDummy(CClub *club, DUMMY_ARG, Int editorLanguageId, WideChar const *name) {}

void OnCopyTownName(WideChar *dst, CClub *club) {
    WideChar const *cityName = L"";
    auto city = GetCity(GetClubExtension(club)->cityId);
    if (city)
        cityName = city->names[CurrentLanguageId].c_str();
    wcscpy(dst, cityName);
}

Bool METHOD OnWriteAppearanceDefsToBinaryDatabase(CBinaryFile *file) {
    Bool result = CallMethodAndReturn<Bool, 0x5A1C60>(file);

    // binary database version 20130012
    file->WriteFourcc('CTRG');
    file->WriteUInt(DBCities().size());
    for (auto &[id, city] : DBCities()) {
        file->WriteInt(city.id);
        file->WriteUChar(city.countryId);
        file->WriteUChar(city.population);
        file->WriteFloat(city.latitude);
        file->WriteFloat(city.longitude);
        file->WriteInt(city.regionId);
        for (UInt i = 0; i < NUM_TRANSLATION_LANGUAGES; i++)
            file->WriteString(city.names[i].c_str());
    }
    file->WriteUInt(DBRegions().size());
    for (auto &[id, region] : DBRegions()) {
        file->WriteInt(region.id);
        file->WriteUChar(region.countryId);
        file->WriteFloat(region.latitude);
        file->WriteFloat(region.longitude);
        for (UInt i = 0; i < NUM_TRANSLATION_LANGUAGES; i++)
            file->WriteString(region.names[i].c_str());
    }
    file->WriteFourcc('CTRG');

    return result;
}

void METHOD OnBinaryFileWriteClubMascot(CBinaryFile *file, DUMMY_ARG, WideChar const *str) {
    auto club = raw_ptr(str, -0xD3C);
    file->WriteInt(GetClubExtension(club)->cityId);
    file->WriteString(str);
}

void METHOD OnReadLeague(void *league, DUMMY_ARG, CKLFile *file) {
    if (file->IsVersionGreaterOrEqual(0x2013, 0x12)) {
        auto ext = GetLeagueExtension(league);
        file->ReadUChar(ext->order);
        file->ReadUChar(ext->numberOfRegions);
        if (ext->numberOfRegions) {
            ext->regions = new LeagueRegion[ext->numberOfRegions];
            for (UInt i = 0; i < ext->numberOfRegions; i++) {
                file->ReadIntAndDelimiter(ext->regions[i].regionID, L',');
                file->ReadUCharAndDelimiter(ext->regions[i].priority, L',');
                file->ReadUChar(ext->regions[i].direction);
            }
        }
    }
    CallMethod<0x5046C0>(league, file);
}

void METHOD OnWriteLeague(void *league, DUMMY_ARG, CKLFile *file, Int countryId) {
    auto ext = GetLeagueExtension(league);
    file->WriteUChar(ext->order);
    file->WriteUChar(ext->numberOfRegions);
    if (ext->numberOfRegions) {
        for (UInt i = 0; i < ext->numberOfRegions; i++) {
            file->WriteIntAndDelimiter(ext->regions[i].regionID, L',');
            file->WriteUCharAndDelimiter(ext->regions[i].priority, L',');
            file->WriteUChar(ext->regions[i].direction);
        }
    }
    CallMethod<0x503640>(league, file);
}

void METHOD OnWriteLeagueToMasterDb(void *league, DUMMY_ARG, CBinaryFile *file) {
    CallMethod<0x4FEE50>(league, file);
    auto ext = GetLeagueExtension(league);
    file->WriteUChar(ext->order);
    file->WriteUChar(ext->numberOfRegions);
    if (ext->numberOfRegions) {
        for (UInt i = 0; i < ext->numberOfRegions; i++) {
            file->WriteInt(ext->regions[i].regionID);
            file->WriteUChar(ext->regions[i].priority);
            file->WriteUChar(ext->regions[i].direction);
        }
    }
}

void PatchCitiesAndRegions(FM::Version v) {
    if (v.id() == VERSION_ED_13) {
        // dialogs
        patch::RedirectCall(0x42A6A5, OnDlgClubConstructor);
        patch::RedirectCall(0x42B06B, OnDlgClubDestructor);
        patch::SetPointer(0x650FF0, OnDlgClubDoDataExchange);
        patch::RedirectCall(0x4BE48E, OnLoadDatabase);
        patch::RedirectCall(0x50B55E, OnLoadDatabase);
        patch::RedirectCall(0x45C858, OnSaveDatabase);
        patch::RedirectCall(0x432FCE, OnDlgClubLoadClub);
        patch::RedirectCall(0x42B823, OnDlgClubLoadClub);
        patch::RedirectCall(0x42B80E, OnDlgClubSaveClub);
        patch::RedirectCall(0x433060, OnDlgClubSaveClub);

        // text database
        patch::RedirectCall(0x4C530E, OnReadClubTown);
        patch::RedirectCall(0x4C5412, OnReadClubAddress);
        patch::RedirectCall(0x4C5539, OnReadClubLatitude);
        patch::RedirectCall(0x4C5547, OnReadClubLongitude);
        patch::NopFromTo(0x4C5AD4, 0x4C5AE6); // CClub::Write (town)
        patch::RedirectCall(0x4C5BDB, OnWriteClubAddress);

        // binary database
        patch::RedirectCall(0x4D95FF, OnWriteAppearanceDefsToBinaryDatabase);
        patch::RedirectCall(0x4D9A10, OnWriteAppearanceDefsToBinaryDatabase);
        patch::Nop(0x4C49B0, 8);
        patch::RedirectCall(0x4C4A44, OnBinaryFileWriteClubMascot);

        // old town references
        patch::RedirectJump(0x42B37A, 0x42B3EA); // CDlgClub::LoadClub
        patch::RedirectCall(0x559D12, OnGetClubTownName); // part of Editor Hotfix - never tested
        patch::RedirectCall(0x4551D4, OnGetClubTownName_NameEditor); // name editor - always return empty name
        patch::RedirectCall(0x4F7C56, OnGetClubTownName_DatabaseProblemTool); // database problem tool (ClubInvalidTown)
        patch::SetUChar(0x4F7C69 + 2, (UChar)NUM_TRANSLATION_LANGUAGES);
        patch::RedirectCall(0x4F7CB8, OnGetClubTownName_DatabaseProblemTool); // database problem tool (ClubUnsupportedChar)
        patch::SetUChar(0x4F7CCB + 2, (UChar)NUM_TRANSLATION_LANGUAGES);
        patch::RedirectCall(0x4F7CA3, OnGetClubName_DatabaseProblemTool);
        patch::RedirectCall(0x556C19, OnGetClubTownName_AllOther);
        patch::RedirectCall(0x55CC7F, OnGetClubTownName_AllOther);
        patch::RedirectCall(0x569352, OnGetClubTownName_AllOther);
        patch::RedirectJump(0x4C1E80, ClubSetTownDummy);
        // CIDResolverToTownName
        patch::SetBytes(0x4C7506, "8B D6 90 90 90 90 90"); // lea edx, [esi+ecx*4+454h] => mov edx, esi
        patch::RedirectCall(0x4C7513, OnCopyTownName);

        // league regions
        patch::RedirectCall(0x50542C, OnReadLeague);
        patch::RedirectCall(0x503D6B, OnWriteLeague);
        patch::RedirectCall(0x4FEEBE, OnWriteLeagueToMasterDb);
    }
}
